---
- name: restart nginx
  systemd:
    name: nginx
    state: restarted
  become: yes

- name: reload nginx
  systemd:
    name: nginx
    state: reloaded
  become: yes

- name: restart php-fpm
  systemd:
    name: "php{{ php_version }}-fpm"
    state: restarted
  become: yes
  when: php_version is defined
